### ISSUE TITLE
Error with Scala 2.13.1 and MyType[Lambda[a => Task[Either[Throwable, a]]]] 

### ISSUE THREAD

**Issue by aksharp** [typelevel/kind-projector#122] opened 2019-10-05 18:43 UTC
Using Scala 2.13.1 and SBT 1.3.2

With type class
```
trait DB[F[_]] {
  def getAll[V]: F[Vector[V]]
}
```

and implementation
```
class MyDB extends DB[Lambda[a => Task[Either[Throwable, a]]]] {
  override def getAll[V]: Task[Either[Throwable, Vector[V]]] = Task { ... }
}
```
get following error
```
Error:scalac: Error: scala.tools.nsc.Global.reporter()Lscala/tools/nsc/reporters/Reporter;
java.lang.NoSuchMethodError: scala.tools.nsc.Global.reporter()Lscala/tools/nsc/reporters/Reporter;
	at d_m.StringParser.parse(StringParser.scala:9)
	at d_m.KindRewriter$MyTransformer.makeTypeParamFromName$1(KindProjector.scala:164)
	at d_m.KindRewriter$MyTransformer.$anonfun$transform$3(KindProjector.scala:221)
	at scala.collection.immutable.List.map(List.scala:219)
	at d_m.KindRewriter$MyTransformer.handleLambda$1(KindProjector.scala:219)
	at d_m.KindRewriter$MyTransformer.validateArgs$1(KindProjector.scala:304)
	at d_m.KindRewriter$MyTransformer.validateLambda$1(KindProjector.scala:312)
	at d_m.KindRewriter$MyTransformer.transform(KindProjector.scala:334)
	at d_m.KindRewriter$MyTransformer.transform(KindProjector.scala:38)
	at scala.reflect.api.Trees$Transformer.transformTrees(Trees.scala:2583)
	at scala.reflect.internal.Trees$AppliedTypeTree.transform(Trees.scala:922)
	at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.transform(TypingTransformers.scala:51)
	at d_m.KindRewriter$MyTransformer.handlePlaceholders$1(KindProjector.scala:272)
	at d_m.KindRewriter$MyTransformer.transform(KindProjector.scala:342)
	at d_m.KindRewriter$MyTransformer.transform(KindProjector.scala:38)
	at scala.reflect.api.Trees$Transformer.transformTrees(Trees.scala:2583)
	at scala.reflect.internal.Trees$Template.transform(Trees.scala:517)
	at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.$anonfun$transform$1(TypingTransformers.scala:47)
	at scala.reflect.api.Trees$Transformer.atOwner(Trees.scala:2625)
	at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.atOwner(TypingTransformers.scala:37)
	at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.transform(TypingTransformers.scala:32)
	at d_m.KindRewriter$MyTransformer.transform(KindProjector.scala:346)
	at d_m.KindRewriter$MyTransformer.transform(KindProjector.scala:38)
	at scala.reflect.api.Trees$Transformer.transformTemplate(Trees.scala:2587)
	at scala.reflect.internal.Trees$ClassDef.$anonfun$transform$2(Trees.scala:335)
	at scala.reflect.api.Trees$Transformer.atOwner(Trees.scala:2625)
	at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.atOwner(TypingTransformers.scala:37)
	at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.atOwner(TypingTransformers.scala:32)
	at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.atOwner(TypingTransformers.scala:24)
	at scala.reflect.internal.Trees$ClassDef.transform(Trees.scala:334)
	at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.transform(TypingTransformers.scala:51)
	at d_m.KindRewriter$MyTransformer.transform(KindProjector.scala:346)
	at d_m.KindRewriter$MyTransformer.transform(KindProjector.scala:38)
	at scala.reflect.api.Trees$Transformer.$anonfun$transformStats$1(Trees.scala:2614)
	at scala.reflect.api.Trees$Transformer.transformStats(Trees.scala:2612)
	at scala.reflect.internal.Trees$PackageDef.$anonfun$transform$1(Trees.scala:316)
	at scala.reflect.api.Trees$Transformer.atOwner(Trees.scala:2625)
	at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.atOwner(TypingTransformers.scala:37)
	at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.atOwner(TypingTransformers.scala:32)
	at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.atOwner(TypingTransformers.scala:24)
	at scala.reflect.internal.Trees$PackageDef.transform(Trees.scala:316)
	at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.$anonfun$transform$2(TypingTransformers.scala:49)
	at scala.reflect.api.Trees$Transformer.atOwner(Trees.scala:2625)
	at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.atOwner(TypingTransformers.scala:37)
	at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.transform(TypingTransformers.scala:32)
	at d_m.KindRewriter$MyTransformer.transform(KindProjector.scala:346)
	at scala.tools.nsc.ast.Trees$Transformer.transformUnit(Trees.scala:162)
	at scala.tools.nsc.transform.Transform$Phase.apply(Transform.scala:36)
	at scala.tools.nsc.Global$GlobalPhase.applyPhase(Global.scala:452)
	at scala.tools.nsc.Global$GlobalPhase.run(Global.scala:397)
	at scala.tools.nsc.Global$Run.compileUnitsInternal(Global.scala:1506)
	at scala.tools.nsc.Global$Run.compileUnits(Global.scala:1490)
	at scala.tools.nsc.Global$Run.compileSources(Global.scala:1482)
	at scala.tools.nsc.Global$Run.compile(Global.scala:1614)
	at xsbt.CachedCompiler0.run(CompilerInterface.scala:130)
	at xsbt.CachedCompiler0.run(CompilerInterface.scala:105)
	at xsbt.CompilerInterface.run(CompilerInterface.scala:31)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sbt.internal.inc.AnalyzingCompiler.call(AnalyzingCompiler.scala:237)
	at sbt.internal.inc.AnalyzingCompiler.compile(AnalyzingCompiler.scala:111)
	at sbt.internal.inc.AnalyzingCompiler.compile(AnalyzingCompiler.scala:90)
	at org.jetbrains.jps.incremental.scala.local.IdeaIncrementalCompiler.compile(IdeaIncrementalCompiler.scala:40)
	at org.jetbrains.jps.incremental.scala.local.LocalServer.compile(LocalServer.scala:35)
	at org.jetbrains.jps.incremental.scala.remote.Main$.make(Main.scala:89)
	at org.jetbrains.jps.incremental.scala.remote.Main$.nailMain(Main.scala:35)
	at org.jetbrains.jps.incremental.scala.remote.Main.nailMain(Main.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.martiansoftware.nailgun.NGSession.run(NGSession.java:319)
```

**Comment by SethTisue** [comment] 2019-10-05 18:52
duplicate of #116

**Closed by SethTisue** 2019-10-05 18:52 UTC
