### ISSUE TITLE
use in parameter position of a function

### ISSUE THREAD

**Issue by ShahOdin** [typelevel/kind-projector#123] opened 2019-10-13 15:45 UTC
I want to write something like: 

```scala 
  def getOrElse[A](either: Either[+*, A], defaultValue: A): A = either.getOrElse(defaultValue)
```

and not have `L` appear in the type-parameter list, but I get 

> Error:type Λ$ takes type parameters
  def getOrElse[A](either: Either[+*, A], defaultValue: A): A = either.getOrElse(defaultValue)

which is understandable. I was just wondering if there is a way of not having a `L` type in the function signature.

**Comment by kubukoz** [comment] 2019-10-13 18:35
Hey, I think you could just say the left side of the Either is Any. By using *, you're treating Either as a *->* kinded type, and these need to be fully applied to have values, which means you can't pass anything as `either`. I'd recommend you use Any (it'll work because Either is covariant) or `_` (any type will match, even for something not covariant like Either).

**Comment by ShahOdin** [comment] 2019-10-13 18:59
@kubukoz Thank you for the clarification about values and types here. `Any` is a good trick but what if the type to be "hide" here was itself a type constructor? 
The actual use-case that brought about the question is this: 

I have a number of calls that I want to `parMapN` over and need to take an instance of: `NonEmptyParallel[M[_], F[_]]` (which I have just that the new versions of the library has only one type-constrctor parameter, but [this](https://github.com/typelevel/cats/commit/58a9fd6da1e0a350fc3b24ffea19f7d008333f5f#diff-2aff592633ecd69c6f25f7d8584c65baR9) is what it was.)

And my method currently looks like this: 

```scala
def foo[FPar[_], F[_]](implicit par: cats.Parallel[F, FPar]):F[Unit]
```  

where FPar is merely an implementation detail which I don't care about. 

I am guessing I can't do anything in that case, right?

**Comment by kubukoz** [comment] 2019-10-13 21:55
I think `_` could work instead of FPar... Haven't tested though. Note that Parallel only takes one type parameter in cats 2.x (binary compatible with 1.x) so that particular problem is gone.

**Comment by ShahOdin** [comment] 2019-10-13 22:00
`_` doesn't work sadly. I get: 

> Error: _$1 takes no type parameters, expected: one
    def foo[F[_]](implicit par: cats.Parallel[F, _]):F[Unit] = ???

I tried: `_[_]` instead which just gave me red underscores in IntelliJ. `*[_]/*[*]` makes intelliJ happy but the compiler gives: 

> Error: type Λ$ takes type parameters
    def foo[F[_]](implicit par: cats.Parallel[F, *[*]]):F[Unit] = ???

**Comment by ShahOdin** [comment] 2019-10-15 19:57
let's say I have: 

```scala
trait M[F[_], G[_]]
```

This compiles: 

```scala
def foo[_[_], F[_]] = ???
```

while actually "using" `_[_]` for a parameter type, namely: 

```scala
def bar[F[_]](implicit m: M[F, _[_]]):F[Unit] = ???
```

doesn't seem to be ok and the compiler says: 

> Error: _$1 does not take type parameters
  def foo[F[_]](implicit m: M[F, _[_]]):F[Unit] = ???

**Comment by barambani** [comment] 2019-10-18 16:53
I think something like this could work ? (assuming you're happy to use kind projector). Is it what you're looking for ?

```scala
def bar[F[_]](implicit m: M[F, λ[α => α]]):F[Unit] = ???
```
```
scala> def bar[F[_]](implicit m: M[F, λ[α => α]]):F[Unit] = ???
bar: [F[_]](implicit m: M[F,[α]α])F[Unit]
```

**Comment by kubukoz** [comment] 2019-10-18 18:42
The above doesn't really work with Parallel.

I tried a few things:

`def foo[F[_]: Monad](implicit P: Parallel[F, G] forSome { type G[_] }): (F[Unit], F[Unit]) => F[Unit] = _ &> _`

This actually allows using Parallel operations inside `foo`, but can't be called as e.g. `foo[IO]`. Also, `forSome` is (or will be) deprecated.

Parallel also is invariant in the second effect type so we can't use a trick like Any or Nothing (even though these types are poly-kinded). If it was `Parallel[+F[_], +G[_]]`, we could've said `Parallel[F, Any]` and things would've worked (probably).

I would say you can't do anything more than keeping `FPar` in your type parameters, or upgrading cats.

**Comment by barambani** [comment] 2019-10-18 19:45
Thanks, well, you're absolutely right. My suggestion wouldn't work with Parallel in the sense that even if something like this it's perfectly legal
```scala
def bar[F[_]: Parallel[*[_], λ[α => α]] ](i1: F[Int], i2: F[Int]): F[Unit] =
    (i1, i2) parMapN ((ii1, ii2) => println(s"Got: $ii1, $ii2}"))
```
we can't provide an instance of `Parallel` for some `F[_]` that's a Monad and anything else (`λ[α => α]`). The second type operator needs to be an `Applicative`, so it would be impossible to provide `Parallel` them or for `F[_]` and `Any`. It's impossible to fulfill the constraints I guess.
But for an `M[F[_], G[_]]` that doesn't have any constraint it should work fine. Anyway, thanks :), this is very interesting.

**Comment by kubukoz** [comment] 2019-10-18 22:58
> Thanks, well, you're absolutely right. My suggestion wouldn't work with Parallel in the sense that even if something like this is perfectly legal
> 
> ```scala
> def bar[F[_]: Parallel[*[_], λ[α => α]] ](i1: F[Int], i2: F[Int]): F[Unit] =
>     (i1, i2) parMapN ((ii1, ii2) => println(s"Got: $ii1, $ii2}"))
> ```

Note that `λ[a => a]` is just `cats.Id`. Something like `bar[IO]` would've worked if there was an implicit instance of `Parallel[IO, Id]`.

(also you shouldn't have side effects in parMapN but you probably know this)

> we can't provide an instance of `Parallel` for some `F[_]` that's a Monad and anything else (`λ[α => α]`).

As mentioned above, that's not "anything else". It's just this one higher-kinded `type Id[A] = A`. "Anything else" is Any.

> The second type operator needs to be an `Applicative`, so it would be impossible to provide `Parallel` for them or for `F[_]` and `Any`. It's impossible to fulfill the constraints I guess.

It has to be implementation-wise, but as a user of the methods like `parMapN`, `parTraverse`, `&>` and others provided by Parallel you don't care what the type of the second effect (the applicative one) is. You should be able to say using an universal quantifier that "I want a Parallel[F, G] for any G". It'll be the caller's responsibility to provide an instance that's lawful, so we need not concern ourselves with that here. The problem is variance, in particular - invariance of Parallel.

> But for an `M[F[_], G[_]]` that doesn't have any constraint it should work fine. Anyway, thanks :), this is very interesting.

It is indeed ;) If we have `M[F[_], +G[_]]` we can use `M[F, Any]` because Any matches any kind. That was the interesting part for me...

When you do M[F, λ[a => a]` you're basically saying you'll accept `M[F, Id]`, so until you try to call that function without having such an instance in scope you won't spot anything weird (a compilation error) :)

**Comment by kubukoz** [comment] 2019-10-21 14:41
@ShahOdin can we close this issue?

**Closed** 2019-10-21 14:42 UTC

**Comment by ShahOdin** [comment] 2019-10-21 14:43
thanks for the nice explanation @kubukoz
